services:

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      ROMAIN_PASSWORD: ${PG_ROMAIN_PASSWORD}
      NAHED_PASSWORD: ${PG_NAHED_PASSWORD}
      BELKACEM_PASSWORD: ${PG_BELKACEM_PASSWORD}
      VELIB_PASSWORD: ${PG_VELIB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-postgres:/docker-entrypoint-initdb.d
    networks:
      - backend

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      ROMAIN_PASSWORD: ${MG_ROMAIN_PASSWORD}
      NAHED_PASSWORD: ${MG_NAHED_PASSWORD}
      BELKACEM_PASSWORD: ${MG_BELKACEM_PASSWORD}
      VELIB_PASSWORD: ${MG_VELIB_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    networks:
      - backend

  python:
    build: ./python
    container_name: python
    restart: unless-stopped
    tty: true
    volumes:
      - ./python/workspace:/workspace
    working_dir: /workspace
    depends_on:
      - postgresql
      - mongodb
    networks:
      - backend
  api:
    build: ./python
    container_name: velib_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./python/workspace:/workspace
    working_dir: /workspace
    depends_on:
      - postgresql
      - mongodb
    networks:
      - backend
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
  cron:
    build: ./python
    container_name: velib_cron
    restart: unless-stopped
    environment:
      MONGO_URL: ${MONGO_URL}
      BDD: db_velib
      PG_LOGIN: velib
      PG_PASSWORD: ${PG_VELIB_PASSWORD}
      PG_HOST: postgresql
      PG_PORT: 5432
      RER_KEY: ${RER_KEY}
      METEO_KEY: ${METEO_KEY}
    volumes:
      - ./python/workspace:/workspace
      - ./python/crontab.txt:/tmp/crontab.template:ro
    working_dir: /workspace
    depends_on:
      - postgresql
      - mongodb
    networks:
      - backend
    command: >
      bash -c "
        {
          echo 'PATH=/app/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';
          echo \"MONGO_URL=$$MONGO_URL\";
          echo \"BDD=$$BDD\";
          echo \"PG_LOGIN=$$PG_LOGIN\";
          echo \"PG_PASSWORD=$$PG_PASSWORD\";
          echo \"PG_HOST=$$PG_HOST\";
          echo \"PG_PORT=$$PG_PORT\";
          echo \"RER_KEY=$$RER_KEY\";
          echo \"METEO_KEY=$$METEO_KEY\";
          cat /tmp/crontab.template;
        } > /etc/cron.d/velib-cron &&
        chmod 0644 /etc/cron.d/velib-cron &&
        touch /workspace/import.log &&
        cron -f
      "
volumes:
  pg_data:
  mongo_data:

networks:
  backend:
    driver: bridge
